Add project
BIBSYSDEV/nva-datamodel pull request #8
Opened 2020-03-24 13:09 UTC by brinxmat

- added Project class
- added class to domain of hasName
- added hasProject with domain Publication
- added hasGrantId property with domain Project and range String
- added hasFinancing body property with domain Project and range String

2020-03-24 13:44 UTC, janbj approved these changes
Very good description.

2020-03-24 13:59 UTC, axthosarouris approved these changes
LGTM

2020-03-24 19:58 UTC, brinxmat commented on ontology.ttl
> +  rdfs:subPropertyOf dcterms:subject ;
Spaces autoformatted

2020-03-25 08:59 UTC, janbj approved these changes

2020-03-25 09:51 UTC, axthosarouris commented on ontology.ttl
> +  rdfs:comment "A Project" .
What is a project? can there be an rdfs:example ?

2020-03-25 09:54 UTC, axthosarouris commented on ontology.ttl
> +  rdfs:comment "The relation linking a Project with an Approval" ;
I am confused. a class has range and the range is itself?

2020-03-25 09:55 UTC, axthosarouris commented on ontology.ttl
> +  rdfs:comment "The grant ID of a Project" ;
Is the comment correct?

2020-03-25 09:56 UTC, axthosarouris requested changes
I think there are some copy-paste errors here.

2020-03-25 13:22 UTC, brinxmat commented on ontology.ttl
> +  rdfs:comment "The relation linking a Project with an Approval" ;
This is an error, classes do not have domain/range. Good catch.

2020-03-25 13:22 UTC, brinxmat commented on ontology.ttl
> +  rdfs:comment "A Project" .
Following communication with PO, we want to support multiple types of Project, so I will subclass Project -> ResearchProject to open for other kinds of project

2020-03-25 13:22 UTC, brinxmat commented on ontology.ttl
> +  rdfs:comment "The grant ID of a Project" ;
No!

2020-03-25 13:43 UTC, axthosarouris approved these changes
There is one more mistake but I do not want to lock stuff since I will be partially available today

2020-03-25 13:43 UTC, axthosarouris commented on ontology.ttl
> +  rdfs:comment "The relation linking a Project with an Approval" .
Comment is wrong?

2020-03-25 13:58 UTC, janbj approved these changes

2020-03-25 13:58 UTC, janbj commented on ontology.ttl
> +  rdfs:comment "The Grant ID of a Project" ;
Specify Research Project?

2020-03-25 21:25 UTC, merged